#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
mkdir -p "$HOME/.local/bin" || true
ln -sf "$PWD/scripts" "$HOME/.local/bin/scripts"

# TODO: do it for vim gh git tmux
for i in vim; do
	cd $i && ./setup
	cd -
done
