#!/bin/sh

if [ -z "$(which vim)" ]; then
	echo Need to install full vim.
	exit 1
fi

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
mkdir -p "$HOME/.vim/autoload" 
ln -sf "$PWD/.vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"

